name: Scrape & Import (Hostinger via SSH tunnel)

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"

permissions:
  contents: read

concurrency:
  group: scrape-import
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      CSV_DIR: ${{ secrets.CSV_DIR != '' && secrets.CSV_DIR || 'scripts' }}
      CSV_NAME: cars.csv
      KRW_EUR: ${{ secrets.KRW_EUR != '' && secrets.KRW_EUR || '0.000615' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system deps (MariaDB client, SSH)
        run: |
          sudo apt-get update
          sudo apt-get install -y mariadb-client openssh-client

      - name: Prepare SSH key (key-only; no password)
        env:
          SSH_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          if ! ssh-keygen -y -f ~/.ssh/id_ed25519 >/dev/null 2>&1; then
            echo "HOSTINGER_SSH_KEY is invalid or passphrase-protected."
            exit 1
          fi
          cat > ~/.ssh/config <<'CFG'
          Host *
            ServerAliveInterval 30
            ServerAliveCountMax 3
            IdentitiesOnly yes
            PreferredAuthentications publickey
            PasswordAuthentication no
            StrictHostKeyChecking no
          CFG

      - name: Sanity SSH auth
        env:
          SSH_HOST: ${{ secrets.HOSTINGER_SSH_HOST }}
          SSH_PORT: ${{ secrets.HOSTINGER_SSH_PORT }}
          SSH_USER: ${{ secrets.HOSTINGER_SSH_USER }}
        run: |
          set -e
          ssh -vvv -o IdentitiesOnly=yes -i ~/.ssh/id_ed25519 \
            -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "echo 'SSH OK'; exit"

      # ---------- SCRAPER ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prepare unique Chrome profile dir
        run: |
          echo "CHROME_USER_DATA_DIR=$RUNNER_TEMP/chrome-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}" >> $GITHUB_ENV
          mkdir -p "$RUNNER_TEMP/chrome-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"

      - name: Clean stale Chrome (best-effort)
        run: |
          pkill -f chrome || true
          pkill -f chromedriver || true

      - name: Install Python requirements
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        env:
          KRW_EUR: ${{ env.KRW_EUR }}
        run: |
          set -euo pipefail
          mkdir -p "$CSV_DIR"
          python scripts/github.py
          test -s "${CSV_DIR}/${CSV_NAME}" || (echo "CSV not found at ${CSV_DIR}/${CSV_NAME}" >&2; exit 1)
          ls -lh "${CSV_DIR}/${CSV_NAME}"

      # ---------- COPY CSV & IMPORT FROM SSH HOST ----------
      - name: Upload CSV to SSH host
        env:
          SSH_HOST: ${{ secrets.HOSTINGER_SSH_HOST }}
          SSH_PORT: ${{ secrets.HOSTINGER_SSH_PORT }}
          SSH_USER: ${{ secrets.HOSTINGER_SSH_USER }}
          CSV_DIR: ${{ env.CSV_DIR }}
          CSV_NAME: ${{ env.CSV_NAME }}
        run: |
          set -euo pipefail
          LOCAL_CSV="$GITHUB_WORKSPACE/${CSV_DIR}/${CSV_NAME}"
          echo "Looking for CSV at: $LOCAL_CSV"
          ls -l "$GITHUB_WORKSPACE/${CSV_DIR}" || true
          test -s "$LOCAL_CSV" || { echo "CSV not found at $LOCAL_CSV"; exit 1; }

          REMOTE_CSV="/tmp/encar_${GITHUB_RUN_ID}_${GITHUB_RUN_ATTEMPT}.csv"
          scp -P "$SSH_PORT" -i ~/.ssh/id_ed25519 "$LOCAL_CSV" \
              "${SSH_USER}@${SSH_HOST}:${REMOTE_CSV}"
          echo "REMOTE_CSV=$REMOTE_CSV" >> "$GITHUB_ENV"

      - name: Import CSV on SSH host → Hostinger MySQL (no SET SESSION)
        env:
          SSH_HOST: ${{ secrets.HOSTINGER_SSH_HOST }}
          SSH_PORT: ${{ secrets.HOSTINGER_SSH_PORT }}
          SSH_USER: ${{ secrets.HOSTINGER_SSH_USER }}
          DB_NAME:  ${{ secrets.DB_DATABASE }}
          DB_USER:  ${{ secrets.DB_USERNAME }}
          DB_PASS:  ${{ secrets.DB_PASSWORD }}
          REMOTE_CSV: ${{ env.REMOTE_CSV }}
        run: |
          set -euo pipefail
          # Pass variables explicitly into the remote shell
          ssh -o IdentitiesOnly=yes -i ~/.ssh/id_ed25519 -p "$SSH_PORT" \
            "$SSH_USER@$SSH_HOST" \
            "DB_HOST='srv1802.hstgr.io' \
             DB_NAME='${DB_NAME}' \
             DB_USER='${DB_USER}' \
             DB_PASS='${DB_PASS}' \
             CSV_PATH='${REMOTE_CSV}' \
             bash -s" <<'REMOTE'
          set -euo pipefail

          # Ensure mariadb client is present (best-effort)
          command -v mariadb >/dev/null 2>&1 || { sudo apt-get update && sudo apt-get install -y mariadb-client || true; }

          echo "Server + identity:"
          MYSQL_PWD="$DB_PASS" mariadb --protocol=TCP --ssl \
            -h "$DB_HOST" -u "$DB_USER" -e "SELECT @@version AS version, CURRENT_USER() AS cur_user, USER() AS login_user;" "$DB_NAME"

          echo "local_infile setting (server):"
          MYSQL_PWD="$DB_PASS" mariadb --protocol=TCP --ssl \
            -h "$DB_HOST" -u "$DB_USER" -e "SHOW VARIABLES LIKE 'local_infile';" "$DB_NAME"

          # Create staging
          MYSQL_PWD="$DB_PASS" mariadb --protocol=TCP --ssl \
            -h "$DB_HOST" -u "$DB_USER" "$DB_NAME" <<'SQL'
          DROP TABLE IF EXISTS stg_encar;
          CREATE TABLE stg_encar (
            prodhuesi        VARCHAR(80),
            modeli           VARCHAR(120),
            varianti         VARCHAR(160),
            viti             VARCHAR(8),
            cmimi_eur        INT,
            kilometrazhi_km  INT,
            karburanti       VARCHAR(40),
            ngjyra           VARCHAR(40),
            transmisioni     VARCHAR(40),
            uleset           VARCHAR(8),
            vin              VARCHAR(40),
            engine_cc        INT,
            images           TEXT,
            listing_url      VARCHAR(512),
            opsionet         MEDIUMTEXT,
            raporti_url      TEXT
          ) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
          SQL

          # Load CSV → staging
          # NOTE: do NOT SET SESSION local_infile — just enable client-side and rely on server setting.
          MYSQL_PWD="$DB_PASS" mariadb --protocol=TCP --ssl --local-infile=1 \
            -h "$DB_HOST" -u "$DB_USER" "$DB_NAME" --execute="
            LOAD DATA LOCAL INFILE '${CSV_PATH}'
            INTO TABLE stg_encar
            CHARACTER SET utf8mb4
            FIELDS TERMINATED BY ','  ENCLOSED BY '\"'
            LINES TERMINATED BY '\n'
            IGNORE 1 LINES
            (prodhuesi, modeli, varianti, viti, cmimi_eur, kilometrazhi_km, karburanti, ngjyra,
             transmisioni, uleset, vin, engine_cc, images, listing_url, opsionet, raporti_url);
          "

          # Ensure final table + unique index (idempotent)
          MYSQL_PWD="$DB_PASS" mariadb --protocol=TCP --ssl \
            -h "$DB_HOST" -u "$DB_USER" -e "CREATE TABLE IF NOT EXISTS vehicles LIKE stg_encar;" "$DB_NAME"

          HAS_IDX="$(MYSQL_PWD="$DB_PASS" mariadb --protocol=TCP --ssl \
            -h "$DB_HOST" -u "$DB_USER" -N -B -e \
            "SELECT COUNT(1) FROM information_schema.statistics
             WHERE table_schema = DATABASE() AND table_name='vehicles' AND index_name='uniq_listing_url';" "$DB_NAME")"
          if [ "$HAS_IDX" -eq 0 ]; then
            MYSQL_PWD="$DB_PASS" mariadb --protocol=TCP --ssl \
              -h "$DB_HOST" -u "$DB_USER" -e \
              "ALTER TABLE vehicles ADD UNIQUE KEY uniq_listing_url (listing_url(255));" "$DB_NAME"
          fi

          # Upsert
          MYSQL_PWD="$DB_PASS" mariadb --protocol=TCP --ssl \
            -h "$DB_HOST" -u "$DB_USER" "$DB_NAME" <<'SQL'
          INSERT INTO vehicles (
            prodhuesi, modeli, varianti, viti, cmimi_eur, kilometrazhi_km, karburanti, ngjyra,
            transmisioni, uleset, vin, engine_cc, images, listing_url, opsionet, raporti_url
          )
          SELECT
            prodhuesi, modeli, varianti, viti, cmimi_eur, kilometrazhi_km, karburanti, ngjyra,
            transmisioni, uleset, vin, engine_cc, images, listing_url, opsionet, raporti_url
          FROM stg_encar
          ON DUPLICATE KEY UPDATE
            prodhuesi=VALUES(prodhuesi),
            modeli=VALUES(modeli),
            varianti=VALUES(varianti),
            viti=VALUES(viti),
            cmimi_eur=VALUES(cmimi_eur),
            kilometrazhi_km=VALUES(kilometrazhi_km),
            karburanti=VALUES(karburanti),
            ngjyra=VALUES(ngjyra),
            transmisioni=VALUES(transmisioni),
            uleset=VALUES(uleset),
            vin=VALUES(vin),
            engine_cc=VALUES(engine_cc),
            images=VALUES(images),
            opsionet=VALUES(opsionet),
            raporti_url=VALUES(raporti_url);
          SQL

          rm -f -- "$CSV_PATH"
          REMOTE
